config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: :new do
    member do
      get :task_file, action: :show, controller: 'task_files'
    end
  end
  resources :projects do
    member do
      resources :tasks, only: :new
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'tasks_map', to: 'tasks#tasks_map'

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/task.rb
class Task < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :text_search,
                  against: %i[name],
                  using: {
                    tsearch: {
                      any_word: true,
                      prefix: true
                    }
                  }

  belongs_to :project
  has_many :task_assignments, dependent: :destroy
  has_many :assigned_users, through: :task_assignments, source: :user

  validates :name, :priority, presence: true
  validate :validate_file_type
  validates :latitude, numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 }
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }

  before_validation :lonlat_geo_point

  def validate_file_type
    return unless file.attached? && !file.content_type.in?(%w[image/jpeg image/png application/pdf video/mp4])

    errors.add(:file, 'must be an image (JPEG/PNG), PDF, or video (MP4) file')
  end

  has_rich_text :description
  has_one_attached :file

  enum priority: {
    low: 'low',
    medium: 'medium',
    high: 'high'
  }

  FILTER_PARAMS = %i[query priority sort project_id].freeze

  scope :for_priority, ->(priority) { priority.present? ? where(priority:) : all }
  scope :search, ->(query) { query.present? ? text_search(query) : all }
  scope :sorted, ->(selection) { selection.present? ? apply_sort(selection) : all }

  def self.apply_sort(selection)
    sort, direction = selection.split('-')
    order("tasks.#{sort} #{direction}")
  end

  def self.filter(filters)
    search(filters['query'])
      .for_priority(filters['priority'])
      .sorted(filters['sort'])
  end

  private

  def lonlat_geo_point
    self.lonlat = RGeo::Geographic.spherical_factory(srid: 4326).point(longitude, latitude)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include Filterable

  before_action :authenticate_user!
  before_action :set_task, only: %i[show edit update destroy]
  before_action :find_project, only: :new

  # GET /tasks or /tasks.json
  def index
    @tasks = filter!(Task, 'tasks').joins(:assigned_users).where('users.id = ?', current_user.id)
  end

  def tasks_map
    @tasks = current_user.assigned_tasks
    respond_to do |format|
      format.html
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    authorize @task
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET /tasks/1/edit
  def edit
    authorize @task
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    authorize @task
    if @task.save
      render turbo_stream: turbo_stream.append(
        'tasks',
        partial: 'task',
        locals: { task: @task }
      )
    else
      render turbo_stream: turbo_stream.replace(
        'task-form',
        partial: 'form',
        locals: { task: @task }
      ), status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    authorize @task
    if @task.update(task_params)
      render turbo_stream: turbo_stream.replace(@task)
    else
      render turbo_stream: turbo_stream.replace(
        'task-form',
        partial: 'form',
        locals: { task: @task }
      ), status: :unprocessable_entity
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    authorize @task
    @task.destroy
    render turbo_stream: turbo_stream.remove(@task)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :project_id, :description, :priority, :longitude, :latitude, :file,
                                 assigned_user_ids: [])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_filter_form.html.erb
<div class="flex mb-6 justify-end">
  <%= form_with url: project ? project_path(project) : tasks_path,
    method: :get,
    class: "flex items-baseline",
    data: {
        turbo_frame: "tasks-list",
        turbo_action: "advance"
    } do |form| %>
    <div class="form-group mr-2">
      <%= form.label :sort, class: "sr-only" %>
      <%= form.select :sort, options_for_select([['Application Date Ascending', 'created_at-asc'], ['Application Date Descending', 'created_at-desc']], selected_value_for_filter('sort', project, params)) %>
    </div>
    <div class="form-group mr-2">
      <%= form.label :priority, class: "sr-only" %>
      <%= form.select :priority, options_for_select(Task.priorities.map{|key, _value| [key.humanize, key]}, selected_value_for_filter('priority', project, params)), { include_blank: 'All priority' } %>
    </div>
    <div class="form-group mr-2">
      <%= form.label :query, class: "sr-only" %>
      <%= form.text_field :query, placeholder: "Search tasks", value: selected_value_for_filter('query', project, params) %>
    </div>
    <%= form.submit "Filter", class: "btn-primary px-3 py-2" %>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "contents", id:"task-form", data: {"modal-target": "form"}) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if action_name == "new" || action_name == "create" %>
    <%= form.hidden_field :project_id, value: task.project.id%>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <div class="mt-1">
      <%= form.text_field :name %>
    </div>
  </div>
  <div class="form-group">
     <%= form.label :description %>
     <div class="mt-1">
        <%= form.rich_text_area :description%>
     </div>
  </div>

  <div class="form-group">
    <%= form.label :priority%>
    <%= form.select :priority, options_for_select(Task.priorities.map{|key, _value| [key.humanize, key]}, task.priority), {}, { class: "mt-1" } %>
  </div>

  <div class="form-group">
    <%= form.label :latitude %>
    <div class="mt-1">
      <%= form.text_field :latitude %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :longitude %>
    <div class="mt-1">
      <%= form.text_field :longitude %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :assigned_user_ids, "Assigned to" %>
    <%= form.select :assigned_user_ids, User.where.not(id: current_user.id).pluck(:email, :id), {}, { multiple: true, data: {controller: "slim"} } %>
  </div>

  <div class="form-group">
    <%= form.label :file %>
     <%= form.file_field :file, accept: 'image/jpeg, image/png, application/pdf, video/mp4' %>
  </div>

  <%= form.submit class: "btn-primary py-2 px-2 mt-5" %>
<% end %>

app/views/tasks/_list.html.erb
<%= turbo_frame_tag "tasks-list" do %>
  <div id="tasks" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
    <% tasks.each do |task|%>
      <%= render '/tasks/task', task: task%>
    <% end %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>" class="w-full">
  <% if controller_name == "projects" || action_name != "show" %>
    <div class="rounded-md shadow-md p-4 bg-gray-200 min-h-[120px]">
      <%= link_to task.name, task_path(task), class:"text-lg font-medium text-primary mb-4 hover:text-accent2", data: { "turbo-frame": "_top" }%>
      <% if task.priority %>
        <div class="w-max px-2 flex justify-center items-center mt-1 mb-2 text-gray-200 text-sm rounded-md <%= priority_color(task.priority)%>"><%=task.priority %></div>
      <% end %>
      <% if policy(task).edit? %>
        <div class="flex justify-end">
          <%= link_to "Edit", edit_task_path(task), class: "btn-secondary px-4 mr-2 text-sm",
          data: {
          action: "click->modal#open",
          turbo_frame: "modal",
        }%>
          <%= button_to "Delete", task_path(task), class:"btn-primary py-1 px-4 text-sm", method: :delete, data: { "turbo-confirm": "Are you sure?" }%>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="bg-white shadow-md rounded-lg p-8">
      <div class="flex items-center justify-between mb-6">
        <h2 class="text-3xl font-semibold"><%= task.name %></h2>
        <% if task.priority %>
          <span class="<%= priority_color(task.priority) %> text-white font-bold py-2 px-4 rounded"><%= task.priority %></span>
        <% end %>
      </div>
      <div class="flex items-center justify-between mb-6">
        <div class="flex items-center space-x-4">
          <span class="bg-accent5 text-white font-bold py-2 px-4 rounded">Project: <%= task.project.name %></span>
          <% if task.assigned_users.include?(current_user) %>
            <span class="bg-accent3 text-white font-bold py-2 px-4 rounded">Assigned by: <%= task.project.user.email %></span>
          <% end %>
        </div>
      </div>
      <% if task.description %>
        <div class="text-lg mb-6"><%= task.description %></div>
      <% end %>
      <% if task.file.attached? %>
        <%= turbo_frame_tag "file", src: task_file_task_path(task), loading: "lazy" do %>
          Loading...
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <h3 class="text-2xl font-semibold text-primary mb-4" id="modal-header">Editing task</h3>
  <button data-action="modal#close" class="absolute top-0 right-0 flex items-center justify-center h-8 w-8 rounded-full focus:outline-none focus:bg-gray-600 hover:bg-gray-600" aria-label="Close modal">
    <%= inline_svg_tag 'close.svg', class: "h-7 w-7 text-gray-800" %>
  </button>
  <div class="mt-4 px-4 text-gray-700">
    <div id="modal-content">
      <%= render "form", task: @task %>
    </div>
  </div>
<% end %>

app/views/tasks/index.html+turbo_frame.erb
<%= render "list", tasks:  @tasks%>

app/views/tasks/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center mb-5">
    <h1 class="font-bold text-4xl">Tasks assigned to you</h1>
  </div>
  <%= render "filter_form" , project: nil%>
  <%= render "list", tasks: @tasks %>
</div>

app/views/tasks/new.html.erb
<%= turbo_frame_tag "modal", class: "ml-auto" do %>
  <h3 class="text-2xl font-semibold text-primary mb-4" id="modal-header">Add a new task</h3>
  <button data-action="modal#close" class="absolute top-0 right-0 flex items-center justify-center h-8 w-8 rounded-full focus:outline-none focus:bg-gray-600 hover:bg-gray-600" aria-label="Close modal">
    <%= inline_svg_tag 'close.svg', class: "h-7 w-7 text-gray-800" %>
  </button>
  <div class="mt-4 px-4 text-gray-700">
    <div id="modal-content">
      <%= render "form", task: @task %>
    </div>
  </div>
<% end %>

app/views/tasks/show.html.erb
<div class="mx-auto md:w-[90%] w-full flex">
  <%= render '/tasks/task', task: @task %>
</div>

app/views/tasks/tasks_map.html.erb
<div class="w-full">
    <h1 class="font-bold text-4xl mb-2">Tasks assigned to you on map view</h1>
     <div data-controller="maps">
        <div data-maps-target="container" class="h-[75vh] w-auto"></div>
    </div>
</div>