config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: :new do
    member do
      get :task_file, action: :show, controller: 'task_files'
    end
  end
  resources :projects do
    member do
      resources :tasks, only: :new
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'tasks_map', to: 'tasks#tasks_map'

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flash.html.erb
<div class="fixed inset-x-0 -bottom-32 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-50 pointer-events-none">
  <div data-controller="alert" class="max-w-sm w-full h-24 shadow-lg rounded px-4 py-3 relative border-l-4 text-white pointer-events-auto <%= flash_class(level) %>">
    <div class="p-2">
      <div class="flex items-start">
        <div class="ml-3 w-0 flex-1 pt-0.5">
          <p class="text-sm leading-5">
            <%= content %>
          </p>
        </div>
        <div class="ml-4 flex-shrink-0 flex">
          <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
            <%= inline_svg_tag 'close.svg', class: 'h-4 w-4 inline-block' %>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag(
  "modal",
  data: {
    "modal-target": "modal",
    action: "turbo:submit-end->modal#handleResponse"
  },
  class: "fixed display-relative min-w-[60%] top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-gray-50 shadow-lg rounded-lg p-6 hidden z-40"
) %>



<!--<div class="fixed top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-white shadow-lg rounded-lg p-6 hidden" id="modalContent">
  <h2 class="text-2xl font-semibold text-primary mb-4">Create Project</h2>
  <form>
    <label for="projectName" class="block text-gray-600 mb-2">Project Name</label>
    <input type="text" id="projectName" class="w-full border-gray-300 border-solid border px-4 py-2 rounded mb-4" placeholder="Enter project name">
    <label for="projectDescription" class="block text-gray-600 mb-2">Project Description</label>
    <textarea id="projectDescription" class="w-full border-gray-300 border-solid border px-4 py-2 rounded mb-4" rows="4" placeholder="Enter project description"></textarea>
    <div class="flex justify-end">
      <button type="submit" class="bg-primary text-white font-bold py-2 px-4 rounded mr-2">Create</button>
      <button type="button" class="bg-secondary text-white font-bold py-2 px-4 rounded" id="closeModal">Cancel</button>
    </div>
  </form>
</div>-->

app/views/shared/_nav_bar.html.erb
<nav class="bg-primary">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between h-16 items-center">
      <div class="flex-shrink-0 flex items-center">
        <!-- Logo or brand name -->
        <%= link_to "ProjectManagement", root_path, class: "text-white text-xl font-bold"%>
      </div>
      <div class="lg:hidden">
        <button class="navbar-burger flex items-center text-white p-3" data-action="navbar#toggle">
          <svg class="block h-4 w-4 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <title>Mobile menu</title>
            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
          </svg>
        </button>
      </div>
      <div class="hidden lg:flex lg:items-center">
        <!-- Navigation links -->
        <%= link_to "Projects", projects_path, class: "text-white hover:text-gray-200 px-3 py-2 rounded-md text-sm font-medium" %>
        <%= link_to "Tasks List", tasks_path, class: "text-white hover:text-gray-200 px-3 py-2 rounded-md text-sm font-medium"%>
        <%= link_to "Tasks Map", tasks_map_path, class: "text-white hover:text-gray-200 px-3 py-2 rounded-md text-sm font-medium"%>
      </div>
      <div class="hidden lg:flex lg:items-center">
        <% if current_user %>
          <%= link_to current_user.email, edit_user_registration_path, class: "text-white hover:text-gray-200 px-3 py-2 rounded-md text-sm font-medium" %>
          <%= button_to "Log Out", destroy_user_session_path, class: "text-white hover:text-gray-200 px-3 py-2 rounded-md text-sm font-medium", method: :delete%>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: "text-white hover:text-gray-200 px-3 py-2 rounded-md text-sm font-medium"%>
        <% end %>
      </div>
    </div>
  </div>
</nav>
<div class="navbar-menu relative z-[9999] hidden" data-navbar-target="menu" data-action="resize@window->navbar#close">
  <div class="navbar-backdrop fixed inset-0 bg-gray-800 opacity-25" data-action="click->navbar#toggle"></div>
  <nav class="fixed top-0 left-0 bottom-0 flex flex-col w-5/6 max-w-sm py-6 px-6 bg-white border-r overflow-y-auto">
    <div class="flex items-center mb-8 justify-between">
      <%= link_to "ProjectManagement", root_path, class: "text-primary text-xl font-bold"%>
      <button class="navbar-close" data-action="navbar#toggle">
        <svg class="h-6 w-6 text-gray-400 cursor-pointer hover:text-gray-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
        </svg>
      </button>
    </div>
    <div>
      <ul>
        <% if current_user %>
          <li class="mb-1">
            <%= link_to current_user.email, edit_user_registration_path, class: "block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded" %>
          </li>
        <% end %>
        <li class="mb-1">
          <%= link_to "Projects", projects_path, class: "block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded" %>
        </li>
        <li class="mb-1">
          <%= link_to "Tasks List", tasks_path, class: "block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded"%>
        </li>
        <li class="mb-1">
          <%= link_to "Tasks Map", tasks_map_path, class: "block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded"%>
        </li>
      </ul>
    </div>
    <div class="mt-auto">
      <div class="pt-6">
        <% if current_user %>
          <%= button_to "Log Out", destroy_user_session_path, class: "btn-primary px-4 py-3", method: :delete%>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn-secondary px-4 py-3 mb-3"%>
        <% end %>
      </div>
    </div>
  </nav>
</div>