config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: :new do
    member do
      get :task_file, action: :show, controller: 'task_files'
    end
  end
  resources :projects do
    member do
      resources :tasks, only: :new
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'tasks_map', to: 'tasks#tasks_map'

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  default_scope { order(created_at: :desc) }

  validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include Filterable

  before_action :authenticate_user!
  before_action :set_project, only: %i[show edit update destroy project_tasks]

  # GET /projects or /projects.json
  def index
    @projects = Project.where(user: current_user).includes(:tasks)
  end

  # GET /projects/1 or /projects/1.json
  def show
    authorize @project
    @tasks = filter!(Task, "project_tasks_#{@project.id}").where(project_id: @project.id)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    authorize @project
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      render turbo_stream: turbo_stream.prepend(
        'projects',
        partial: 'project',
        locals: { project: @project }
      )
    else
      render turbo_stream: turbo_stream.replace(
        'project-form',
        partial: 'form',
        locals: { project: @project }
      ), status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    authorize @project
    if @project.update(project_params)
      render turbo_stream: turbo_stream.replace(@project)
    else
      render turbo_stream: turbo_stream.replace(
        'project-form',
        partial: 'form',
        locals: { project: @project }
      ), status: :unprocessable_entity
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    authorize @project
    @project.destroy
    render turbo_stream: turbo_stream.remove(@project)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents", id: "project-form", data: {"modal-target": "form"}) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <div class="mt-1">
      <%= form.text_field :name %>
    </div>
  </div>

  <%= form.submit class: "btn-primary py-2 px-2 mt-5" %>
<% end %>

app/views/projects/_project.html.erb
<!--<div id="<%#= dom_id project %>">-->
<%# if action_name != "show" %>
<%#= project.name %>
<%#= link_to "Show this project", project, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
<%#= link_to 'Edit this project', edit_project_path(project), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
<!--    <hr class="mt-6">-->
<%# end %>
<!--</div>-->
<div id="<%= dom_id project %>">
  <% if action_name != "show" %>
    <div class="rounded-md shadow-md p-4 bg-gray-100">
      <a href="<%= project_path(project)%>" class="text-lg font-medium text-primary mb-4 hover:text-accent2"><%= project.name %></a>
      <div class="flex justify-end">
        <%= link_to "Edit", edit_project_path(project), class: "btn-secondary px-4 mr-2 text-sm",
          data: {
          action: "click->modal#open",
          turbo_frame: "modal",
        }%>
        <%= button_to "Delete", project_path(project), class:"btn-primary py-1 px-4 text-sm", method: :delete, data: { "turbo-confirm": "Are you sure?" }%>
      </div>
    </div>
  <% else %>
    <div class="bg-secondary text-gray-200 py-6 px-8">
      <h2 class="text-2xl font-semibold mb-4"><%= project.name %></h2>
    </div>
    <div class="container mx-auto mt-8">
      <div class="flex justify-between items-center mb-5">
        <h3 class="text-xl font-semibold">Task List</h3>
        <%= link_to 'New task', new_task_path(project_id: project.id),
          class: "btn-secondary px-5 py-3",
          data: {
            action: "click->modal#open",
            turbo_frame: "modal",
          } %>
      </div>

      <%= render "/tasks/filter_form", project: project %>
      <%= render "/tasks/list", tasks: tasks%>
    <% end %>
  </div>

app/views/projects/edit.html.erb
<!--<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing project</h1>

  <%#= render "form", project: @project %>-->
<!---->
  <%#= link_to "Show this project", @project, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%#= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
<!--</div>-->

<%= turbo_frame_tag "modal" do %>
  <h3 class="text-2xl font-semibold text-primary mb-4" id="modal-header">Editing project</h3>
  <button data-action="modal#close" class="absolute top-0 right-0 flex items-center justify-center h-8 w-8 rounded-full focus:outline-none focus:bg-gray-600 hover:bg-gray-600" aria-label="Close modal">
    <%= inline_svg_tag 'close.svg', class: "h-7 w-7 text-gray-800" %>
  </button>
  <div class="mt-4 px-4 text-gray-700">
    <div id="modal-content">
      <%= render "form", project: @project %>
    </div>
  </div>
<% end %>

app/views/projects/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Projects</h1>
    <%= link_to 'New project', new_project_path,
      class: "btn-secondary px-5 py-3",
      data: {
        action: "click->modal#open",
        turbo_frame: "modal",
      } %>
  </div>
  <div id="projects" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
    <%= render @projects %>
  </div>
</div>

app/views/projects/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <h3 class="text-2xl font-semibold text-primary mb-4" id="modal-header">Add a new project</h3>
  <button data-action="modal#close" class="absolute top-0 right-0 flex items-center justify-center h-8 w-8 rounded-full focus:outline-none focus:bg-gray-600 hover:bg-gray-600" aria-label="Close modal">
    <%= inline_svg_tag 'close.svg', class: "h-7 w-7 text-gray-800" %>
  </button>
  <div class="mt-4 px-4 text-gray-700">
    <div id="modal-content">
      <%= render "form", project: @project %>
    </div>
  </div>
<% end %>

app/views/projects/show.html+turbo_frame.erb
<%= render "/tasks/list", tasks:  @tasks%>

app/views/projects/show.html.erb
<div>
  <div class="mx-auto">
    <%= render 'project', project: @project, tasks: @tasks %>
  </div>
</div>